export const CHANGE_SHOW_PERIOD = 'CHANGE_SHOW_PERIOD';
export const SET_CURRENCY_CODES = 'SET_CURRENCY_CODES';
export const SET_CURRENCY_HISTORY = 'SET_CURRENCY_HISTORY';
export const SET_DATE = 'SET_DATE';
