export const SET_CURRENCY_CODES = 'SET_CURRENCY_CODES';
export const SET_CURRENCY_HISTORY = 'SET_CURRENCY_HISTORY';
export const SET_DATE = 'SET_DATE';
export const SET_MAIN_CURRENCY = 'SET_MAIN_CURRENCY';
export const FETCH_MAIN_CURRENCY = 'FETCH_MAIN_CURRENCY';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_END = 'REQUEST_END';
